"""Add missing room fields for modes

Revision ID: 010a04de9981
Revises: add_paypal_billing_v1
Create Date: 2026-04-12 05:02:54.429838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '010a04de9981'
down_revision: Union[str, Sequence[str], None] = 'add_paypal_billing_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    insp = inspect(conn)
    return table_name in insp.get_table_names()


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    if not table_exists(table_name):
        return False
    conn = op.get_bind()
    insp = inspect(conn)
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """Upgrade schema."""
    # Drop Stripe-related objects if they exist (idempotent)
    if table_exists('stripe_webhook_events'):
        op.drop_index('ix_stripe_webhook_events_created_at', table_name='stripe_webhook_events', if_exists=True)
        op.drop_index('ix_stripe_webhook_events_stripe_event_id', table_name='stripe_webhook_events', if_exists=True)
        op.drop_table('stripe_webhook_events')
    
    if table_exists('stripe_customers'):
        op.drop_index('ix_stripe_customers_stripe_customer_id', table_name='stripe_customers', if_exists=True)
        op.drop_table('stripe_customers')
    
    if table_exists('invoices') and column_exists('invoices', 'stripe_invoice_id'):
        op.drop_index('ix_invoices_stripe_invoice_id', table_name='invoices', if_exists=True)
        op.drop_column('invoices', 'stripe_invoice_id')
    
    if table_exists('paypal_webhook_events'):
        try:
            op.drop_constraint('paypal_webhook_events_paypal_event_id_key', 'paypal_webhook_events', type_='unique')
        except:
            pass  # Constraint may not exist
    
    if table_exists('plans') and column_exists('plans', 'stripe_price_id'):
        op.drop_index('ix_plans_stripe_price_id', table_name='plans', if_exists=True)
        op.drop_column('plans', 'stripe_price_id')
    
    # Add new room columns (add_column is idempotent in Alembic)
    op.add_column('rooms', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('mode', sa.String(), server_default='conversation', nullable=False))
    op.add_column('rooms', sa.Column('invite_token', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('device_session_id', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('mic_a_lang', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('mic_b_lang', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('broadcaster_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True))
    op.add_column('rooms', sa.Column('available_langs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('rooms', sa.Column('default_lang', sa.String(), nullable=True))
    op.create_index(op.f('ix_rooms_slug'), 'rooms', ['slug'], unique=True)
    op.create_unique_constraint(None, 'rooms', ['invite_token'])
    op.create_foreign_key(None, 'rooms', 'users', ['broadcaster_id'], ['id'])
    
    if column_exists('rooms', 'advanced_policy'):
        op.drop_column('rooms', 'advanced_policy')
    
    # Drop Stripe subscription columns if they exist
    if table_exists('subscriptions'):
        op.drop_index('ix_subscriptions_stripe_customer_id', table_name='subscriptions', if_exists=True)
        op.drop_index('ix_subscriptions_stripe_subscription_id', table_name='subscriptions', if_exists=True)
        if column_exists('subscriptions', 'stripe_subscription_id'):
            op.drop_column('subscriptions', 'stripe_subscription_id')
        if column_exists('subscriptions', 'stripe_customer_id'):
            op.drop_column('subscriptions', 'stripe_customer_id')
    
    if table_exists('usage_records'):
        op.drop_index('ix_usage_records_synced_to_stripe', table_name='usage_records', if_exists=True)
        if column_exists('usage_records', 'stripe_sync_at'):
            op.drop_column('usage_records', 'stripe_sync_at')
        if column_exists('usage_records', 'synced_to_stripe'):
            op.drop_column('usage_records', 'synced_to_stripe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('synced_to_stripe', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('usage_records', sa.Column('stripe_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_usage_records_synced_to_stripe', 'usage_records', ['synced_to_stripe'], unique=False)
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_subscriptions_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index('ix_subscriptions_stripe_customer_id', 'subscriptions', ['stripe_customer_id'], unique=False)
    op.add_column('rooms', sa.Column('advanced_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_slug'), table_name='rooms')
    op.drop_column('rooms', 'default_lang')
    op.drop_column('rooms', 'available_langs')
    op.drop_column('rooms', 'broadcaster_id')
    op.drop_column('rooms', 'mic_b_lang')
    op.drop_column('rooms', 'mic_a_lang')
    op.drop_column('rooms', 'device_session_id')
    op.drop_column('rooms', 'expires_at')
    op.drop_column('rooms', 'invite_token')
    op.drop_column('rooms', 'mode')
    op.drop_column('rooms', 'slug')
    op.add_column('plans', sa.Column('stripe_price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_plans_stripe_price_id', 'plans', ['stripe_price_id'], unique=False)
    op.create_unique_constraint('paypal_webhook_events_paypal_event_id_key', 'paypal_webhook_events', ['paypal_event_id'])
    op.add_column('invoices', sa.Column('stripe_invoice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_invoices_stripe_invoice_id', 'invoices', ['stripe_invoice_id'], unique=True)
    op.create_table('stripe_customers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='stripe_customers_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stripe_customers_pkey'),
    sa.UniqueConstraint('org_id', name='stripe_customers_org_id_key')
    )
    op.create_index('ix_stripe_customers_stripe_customer_id', 'stripe_customers', ['stripe_customer_id'], unique=True)
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='stripe_webhook_events_org_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='stripe_webhook_events_pkey')
    )
    op.create_index('ix_stripe_webhook_events_stripe_event_id', 'stripe_webhook_events', ['stripe_event_id'], unique=True)
    op.create_index('ix_stripe_webhook_events_created_at', 'stripe_webhook_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
