"""verify

Revision ID: 89bde9cf1304
Revises: 012_room_vis_sync
Create Date: 2026-03-30 19:12:14.698063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89bde9cf1304'
down_revision: Union[str, Sequence[str], None] = '012_room_vis_sync'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'target_langs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('rooms', 'primary_lang',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('transcripts', sa.Column('org_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True))
    op.add_column('transcripts', sa.Column('speaker_identity', sa.String(), nullable=True))
    op.add_column('transcripts', sa.Column('is_ai', sa.Boolean(), nullable=False, server_default="false"))
    op.drop_index('ix_transcripts_session_id', table_name='transcripts')
    op.create_foreign_key(None, 'transcripts', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.create_index('ix_transcripts_session_id', 'transcripts', ['session_id'], unique=False)
    op.drop_column('transcripts', 'is_ai')
    op.drop_column('transcripts', 'speaker_identity')
    op.drop_column('transcripts', 'org_id')
    op.alter_column('rooms', 'primary_lang',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'target_langs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###
