"""add_join_request_and_approval

Revision ID: 95a200a9254f
Revises: 009_add_target_langs
Create Date: 2026-03-26 18:40:37.412901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a200a9254f'
down_revision: Union[str, Sequence[str], None] = '009_add_target_langs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('room_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('identity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_room_id'), 'join_requests', ['room_id'], unique=False)
    op.add_column('rooms', sa.Column('requires_approval', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'requires_approval')
    op.drop_index(op.f('ix_join_requests_room_id'), table_name='join_requests')
    op.drop_table('join_requests')
    # ### end Alembic commands ###
